config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {registrations: "registrations" }
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'welcome/predictions'
  post 'welcome/login/verifyUser', to: 'log_in#verifyUser'
  
  get 'welcome/performance'
  get 'welcome/sign_up/get_careers', to: 'sign_up#get_careers'
  post 'welcome/sign_up/create_student', to: 'sign_up#create_student'
  
  get 'welcome/profile'
  post 'welcome/profile/update', to: 'welcome#updateProfile'

  get 'welcome/signedin'
  get 'welcome/studyplan'
  get 'welcome/studentprogress'

  get  'welcome/signedin/get_careers', to: 'signedin#get_careers'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/career.rb
class Career < ApplicationRecord
    has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    belongs_to :career
    has_one :student_progress
end

app/models/student_progress.rb
class StudentProgress < ApplicationRecord
    belongs_to :student
    has_many :studied_subjects
end

app/models/studied_subject.rb
class StudiedSubject < ApplicationRecord
    belongs_to :student_progress
    belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :studied_subjects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/log_in_controller.rb
class LogInController < ApplicationController

  def verifyUser
    res = false

    if (Student.where("email = ? AND pass = ?", params[:email], params[:pass]).take != nil)
      res = true
    end

    render json: {res: res}
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    private
    def sign_up_params
        params.require(:student).permit(:control_number, :name, :email, :career_id, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:student).permit(:control_number, :name, :email, :career_id, :password, :password_confirmation, :current_password)
    end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController

  def get_students
    subjects = Student.all
    render json: subjects
  end
  
  def get_careers
    carreras = Career.all
    render json: carreras
  end

  def create_student
    Student.create(control_number: params[:noControl], email: params[:correo], pass: params[:pass], name: params[:nombre], career_id: params[:carrera_id])
    render json: {}
  end
end

app/controllers/signedin_controller.rb
class SignedinController < ApplicationController
    def get_careers
        carreras = Career.all
        render json: carreras
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :authenticate_student!

    def index
        if student_signed_in?
            # redirect_to welcome_signedin_path
        else
            redirect_to new_student_session_path
        end
    end

    def profile
        @career = Career.find_by(id: current_student.career_id)
    end

    def updateProfile
        user = Student.find_by(id: current_student.id)
        user.name = params[:name]
        user.control_number = params[:control_number]
        user.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_in_helper.rb
module LogInHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/signedin_helper.rb
module SignedinHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrganizaTec</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'flexbox' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width"/>
  </head>

  <body>
  <% if student_signed_in? %>
  <p>Hello, <%= current_student.email %> - <%= link_to "Sign_out", destroy_student_session_path, :method => 'delete' %> - 
    <%= link_to "Home", root_path, :method => 'get' %>
  </p>
  <br/>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<%= react_component("welcome/Welcome") %>

app/views/welcome/login.html.erb
<%= react_component("welcome/LogIn") %>

app/views/welcome/performance.html.erb
<%= react_component("welcome/PerformanceData") %>

app/views/welcome/predictions.html.erb
<%= react_component("welcome/Predictions") %>

app/views/welcome/profile.html.erb
<%= react_component("welcome/Profile", {user: current_student, userCareer: @career}) %>

app/views/welcome/signedin.html.erb
<%= react_component("welcome/SignedIn", {student_email: current_student.email, student: current_student}) %>

app/views/welcome/signup.html.erb
<%= react_component("welcome/Signup") %>

app/views/welcome/studentprogress.html.erb
<%= react_component("welcome/StudentProgress") %>

app/views/welcome/studyplan.html.erb
<%= react_component("welcome/StudyPlan") %>